# Konfigurasi tombol "Sponsor" di GitHub
github: [setiapam]

# Anda juga bisa menambahkan tautan kustom untuk Trakteer, Saweria, atau Ko-fi di sini:
# custom: ['https://trakteer.id/YOUR_USERNAME', 'https://saweria.co/YOUR_USERNAME']
